services:
  postgres:
    image: postgres:17
    container_name: webhooksdb
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: webhooks
    ports:
      - '5434:5432'
    